In [ ]:
import requests 
import pandas as pd
from dotenv import load_dotenv
from os import getenv
from sqlalchemy import create_engine, Engine


load_dotenv()

True

In [2]:
BASE_URL = "https://api.coingecko.com/api/v3"
API_KEY=getenv("API_KEY")

In [ ]:
# function that pulls coin list from coinGecko
end_point = "/coins/list"
url = BASE_URL + end_point   
headers = {
    'accept': 'application/json',
    'x-cg-demo-api-key':API_KEY
}
   

response = requests.get(url, headers=headers)

df = pd.DataFrame(response.json())
df.head()

,id,symbol,name
0,_,gib,༼ つ ◕_◕ ༽つ
1,000-capital,000,000 Capital
2,01111010011110000110001001110100-token,01111010011110000110001001110100,01111010011110000110001001110100
3,01112131415161718192021222324252-token,1234567891,01112131415161718192021222324252
4,01-token,01,01

In [4]:
df[df['id']=='ethereum']

            id symbol      name
5564  ethereum    eth  Ethereum

In [17]:
# function pulls crypto prices every 5 minute
coin_id = 'ethereum'
endpoint = f'/coins/{coin_id}/market_chart'
url = BASE_URL + endpoint
params = {
    'vs_currency': 'usd',
    'days': 1
}

headers = {

'accept': "application/json",
'x-cg-demo-api-key': API_KEY

}

response = requests.get(url, headers=headers, params=params)
print(response.json())

#df_crypto_price = pd.DataFrame(response.json())
#print(df_crypto_price.head())
data = response.json()
print(type(data))
prices = data['prices']
market_caps = data['market_caps']
total_volumes   = data['total_volumes']
prices 
market_caps 
total_volumes  

df_prices = pd.DataFrame(prices, columns=['timestamp', 'price'])
df_market_caps = pd.DataFrame(market_caps, columns = ['timestamp', 'market_cap'] )
df_total_volumes = pd.DataFrame(total_volumes, columns= ['timestamp', 'total_volume'])

df_market_chart= (

 df_prices.merge(df_market_caps, on='timestamp', how='inner')
.merge(df_total_volumes, on='timestamp', how='inner')


)


df_market_chart['timestamp'] = pd.to_datetime(df_market_chart['timestamp'], unit='ms')
df_market_chart.head(10)

{'prices': [[1773240610641, 2069.5606682698317], [1773240910796, 2067.7865171886765], [1773241283284, 2064.125686927166], [1773241515517, 2056.7996827684187], [1773241833588, 2051.68793430254], [1773242196864, 2045.7415418820585], [1773242411654, 2048.313716181834], [1773242753000, 2056.114305110164], [1773243054951, 2049.8466979761442], [1773243311499, 2039.9390146305102], [1773243611583, 2043.7092696712514], [1773243900605, 2043.1270011774945], [1773244261203, 2041.676380107649], [1773244571471, 2049.2092209804814], [1773244892795, 2050.374673174742], [1773245132069, 2051.7584017964837], [1773245432298, 2052.296881724067], [1773245742795, 2053.828323946492], [1773246023242, 2054.9831701973512], [1773246331190, 2055.746445775943], [1773246655258, 2056.5486307376264], [1773246915286, 2060.952441436], [1773247260930, 2062.6355069232486], [1773247510754, 2063.441363397162], [1773247860576, 2067.7730244068634], [1773248161384, 2068.051296806409], [1773248423520, 2066.878860447783], [1773248725336, 2074.780282968569], [1773249022828, 2073.8878625716966], [1773249362144, 2072.0943775037294], [1773249611856, 2072.990054529918], [1773249920915, 2076.7542729511074], [1773250223780, 2082.548453059085], [1773250521185, 2075.680956410802], [1773250837091, 2064.5226524945842], [1773251151188, 2069.2448510185113], [1773251411737, 2068.0944809530893], [1773251716891, 2067.6528690155624], [1773252013083, 2068.064535201132], [1773252334359, 2070.5812976422567], [1773252660685, 2067.4451252692456], [1773252933873, 2068.1139916458305], [1773253200637, 2068.5242272016535], [1773253522005, 2071.2174631851844], [1773253945148, 2073.2543056628356], [1773254160572, 2074.324482571939], [1773254501205, 2069.86059116585], [1773254750702, 2069.0316592590348], [1773255022325, 2071.2669390829387], [1773255343842, 2077.1367014170496], [1773255710516, 2076.8758988735935], [1773255960717, 2074.8088458235356], [1773256308277, 2072.2615042638986], [1773256571756, 2071.540702363698], [1773256805807, 2071.428140098182], [1773257103457, 2072.9018052666975], [1773257425578, 2072.5100097347554], [1773257712294, 2073.539637462524], [1773258000565, 2075.465300544664], [1773258360620, 2074.8754001051666], [1773258660606, 2074.2898955092287], [1773258941885, 2076.7480484403864], [1773259241374, 2075.593806475984], [1773259548100, 2072.633452333002], [1773259801107, 2071.3849168470265], [1773260150646, 2069.2186882601163], [1773260446665, 2070.9839824171854], [1773260760469, 2070.5800531602617], [1773261045926, 2069.5622884521786], [1773261321668, 2068.9942003781894], [1773261624602, 2069.553682783536], [1773261917066, 2070.4289231951184], [1773262221983, 2070.6925039777107], [1773262536778, 2067.654481961724], [1773262835716, 2069.333831413827], [1773263111641, 2067.836657048506], [1773263441756, 2070.0299209847676], [1773263753231, 2065.8417430859326], [1773264093150, 2065.477506819818], [1773264313667, 2066.4937613874804], [1773264651554, 2066.412299264393], [1773264942107, 2068.4947009663115], [1773265245600, 2069.5902594162094], [1773265532804, 2068.7874558917233], [1773265874240, 2070.73275962656], [1773266120750, 2072.795126719725], [1773266471567, 2073.043033585383], [1773266734483, 2071.2977720755343], [1773267043713, 2070.829020752945], [1773267363178, 2080.2877934447724], [1773267613553, 2077.4319021586775], [1773267912501, 2072.5132730781465], [1773268232948, 2069.5372708437076], [1773268511424, 2067.9381940284875], [1773268813292, 2062.7276971157194], [1773269124161, 2064.386275652541], [1773269426458, 2065.7853273507385], [1773269731890, 2062.0940405876363], [1773270080569, 2063.2677032161164], [1773270341226, 2063.4435949126087], [1773270714104, 2062.64581055313], [1773270960526, 2062.182412199071], [1773271313087, 2060.37741219024], [1773271560836, 2059.0834520633716], [1773271820602, 2059.6697852531306], [1773272124836, 2057.151663910095], [1773272453574, 2058.249879018678], [1773272745294, 2056.61662193455], [1773273031999, 2050.7431271425235], [1773273332053, 2051.7311684113824], [1773273646206, 2052.1648597026033], [1773273940875, 2050.839811007407], [1773274241757, 2052.442622217846], [1773274542941, 2052.9462018875442], [1773274881885, 2053.318846508596], [1773275163933, 2056.446507504976], [1773275480707, 2054.1588165899143], [1773275731183, 2052.88037963262], [1773276023576, 2054.2123447387617], [1773276333299, 2056.1407782241245], [1773276613470, 2055.493976259708], [1773276938973, 2055.8247047299], [1773277242533, 2055.842605775967], [1773277512268, 2048.1548600471883], [1773277816583, 2046.837297032661], [1773278141929, 2047.7076152651437], [1773278431221, 2049.520193461032], [1773278745094, 2049.5664005443923], [1773279050928, 2049.848664494891], [1773279353007, 2046.2169337407636], [1773279666626, 2048.093881471397], [1773280003629, 2051.567916989037], [1773280252012, 2048.0485807147766], [1773280512107, 2046.3572665943689], [1773280811108, 2045.7752971211548], [1773281144382, 2045.5392841341409], [1773281445996, 2045.380236751701], [1773281751111, 2044.5718272200845], [1773282101525, 2039.0009589966216], [1773282360461, 2039.0623416669168], [1773282691218, 2039.8413720782894], [1773282960869, 2039.0649413677677], [1773283271639, 2031.1833656221627], [1773283560666, 2032.6921982100298], [1773283841898, 2030.5248105926987], [1773284152869, 2024.4248911160726], [1773284489561, 2024.9123610651618], [1773284715141, 2026.6766321695768], [1773285012741, 2026.828303798151], [1773285316134, 2025.9298731876336], [1773285616521, 2026.918383437789], [1773285920843, 2030.8813590711982], [1773286217140, 2028.640473472173], [1773286512243, 2033.2418600697588], [1773286824363, 2031.8214761297943], [1773287111122, 2031.6972773306231], [1773287400615, 2020.7051460448545], [1773287713617, 2022.3481845079016], [1773288013726, 2023.1107526208427], [1773288347351, 2025.4594853232836], [1773288660728, 2028.2026537717632], [1773288924098, 2028.3665427830733], [1773289241120, 2029.2313291573155], [1773289535487, 2027.4435977990745], [1773289813069, 2026.8561786538414], [1773290100808, 2027.6504718074084], [1773290414155, 2025.9768584285982], [1773290713150, 2025.2046244988867], [1773291021433, 2023.2520953817725], [1773291343504, 2022.9083770050918], [1773291653797, 2022.744927476898], [1773291921434, 2025.1058847266158], [1773292240684, 2025.2356455387412], [1773292531311, 2024.763763513227], [1773292884576, 2023.3215543721847], [1773293160610, 2020.8525790025399], [1773293502992, 2021.3972915529528], [1773293773248, 2023.9379802207663], [1773294043250, 2024.528250601718], [1773294335828, 2026.8398113356313], [1773294612371, 2024.9803583763528], [1773294913114, 2025.0096747258187], [1773295260631, 2026.3321576482126], [1773295531453, 2027.5016166486266], [1773295920528, 2027.1536268956434], [1773296156314, 2028.3833679469128], [1773296453220, 2028.2264238356704], [1773296731238, 2028.9935868309742], [1773297033013, 2030.0831660261085], [1773297321842, 2030.162282600643], [1773297722539, 2027.694063474384], [1773297951950, 2029.294065207227], [1773298253665, 2029.9481908985517], [1773298562313, 2030.0415836787522], [1773298843367, 2029.96873148329], [1773299132180, 2030.2644618135898], [1773299453439, 2027.3206586918986], [1773299782564, 2028.9065449193631], [1773300060538, 2029.12482305636], [1773300360836, 2030.5404913116558], [1773300653687, 2033.2143236367097], [1773300931503, 2038.593055045476], [1773301233755, 2037.5032777580207], [1773301510629, 2036.8789030054043], [1773301822013, 2039.005418363517], [1773302124565, 2039.8292116718715], [1773302442106, 2040.0838408254044], [1773302741918, 2043.7124448730042], [1773303054452, 2038.918107759539], [1773303376165, 2039.4450970861449], [1773303660726, 2049.3701890117763], [1773303952101, 2049.1053901437535], [1773304254036, 2044.6984270674845], [1773304571918, 2046.02231536473], [1773304871112, 2045.832709866481], [1773305160861, 2044.0227669809242], [1773305510947, 2047.0528560885155], [1773305760684, 2047.59985648458], [1773306041964, 2047.2426954416273], [1773306352670, 2047.972250883228], [1773306732675, 2044.607535184013], [1773306954659, 2043.1708115138513], [1773307204033, 2041.701660740681], [1773307503541, 2040.513351308468], [1773307821673, 2041.533055367199], [1773308113364, 2041.293170412169], [1773308421862, 2043.1213141818164], [1773308727328, 2056.302118339795], [1773309013783, 2054.2556791782495], [1773309340837, 2055.2697960756886], [1773309647234, 2055.689429911168], [1773309960542, 2055.684362637055], [1773310251874, 2054.2015890049356], [1773310512238, 2054.145590454836], [1773310822499, 2057.360802271902], [1773311120834, 2061.310052561906], [1773311421572, 2062.2753845204425], [1773311714987, 2065.510306691405], [1773312015562, 2069.0256553466693], [1773312304309, 2070.6855696630946], [1773312642189, 2071.4288889513955], [1773312943378, 2070.484285497153], [1773313251556, 2069.9405147963735], [1773313543170, 2069.9294165756396], [1773313811016, 2070.5831876095517], [1773314122222, 2068.374463927424], [1773314422713, 2069.968233248232], [1773314731614, 2071.239030162798], [1773315040886, 2070.168458105368], [1773315343446, 2070.606271578956], [1773315632563, 2073.718074742974], [1773315960658, 2074.2773319215544], [1773316260573, 2070.984903921134], [1773316513314, 2064.6437024356464], [1773316842767, 2063.3666944041206], [1773317146983, 2060.491035929884], [1773317440698, 2058.937223447513], [1773317745173, 2059.842747876252], [1773318040824, 2062.264130123008], [1773318360543, 2064.634619701193], [1773318660612, 2065.123216096553], [1773318943905, 2061.1083489637363], [1773319256826, 2062.31393654193], [1773319532914, 2066.44691999377], [1773319834144, 2069.9123092473346], [1773320138556, 2064.7755265302253], [1773320472270, 2065.512796966676], [1773320746915, 2066.862926505607], [1773321041553, 2067.0889277342776], [1773321350774, 2065.5512442038244], [1773321653286, 2060.619289214242], [1773321960860, 2055.610894844778], [1773322260619, 2056.1978596578588], [1773322512422, 2062.88166695791], [1773322852125, 2072.8481090960317], [1773323131338, 2070.600288248042], [1773323423519, 2063.347083603562], [1773323750885, 2063.2725686207277], [1773324052403, 2064.995716696748], [1773324342035, 2078.2251197299943], [1773324643544, 2077.5768920341875], [1773324960583, 2080.9106841588027], [1773325280896, 2075.209428168125], [1773325511380, 2071.902372873578], [1773325823304, 2061.2145495982163], [1773326110482, 2050.794749135366], [1773326410919, 2046.473801483535], [1773326700424, 2041.7048184183268], [1773326931000, 2048.584784867024]], 'market_caps': [[1773240610641, 250268401809.95288], [1773240910796, 249565293914.10178], [1773241283284, 249310488800.96124], [1773241515517, 248846826440.26892], [1773241833588, 248095023710.75403], [1773242196864, 248095023710.75403], [1773242411654, 247055765039.6944], [1773242753000, 248034204322.76538], [1773243054951, 247895537585.6385], [1773243311499, 245681683635.38132], [1773243611583, 246348065350.53763], [1773243900605, 246684460807.86227], [1773244261203, 246280769146.6635], [1773244571471, 246992228497.5152], [1773244892795, 247404047903.83527], [1773245132069, 247635891761.02493], [1773245432298, 247711890836.7815], [1773245742795, 247711890836.7815], [1773246023242, 247977175712.0486], [1773246331190, 247967028422.08093], [1773246655258, 248251254602.40552], [1773246915286, 248740475631.52264], [1773247260930, 249112231623.30728], [1773247510754, 248915598193.31735], [1773247860576, 249529883756.48224], [1773248161384, 249666273313.6544], [1773248423520, 249360154343.57532], [1773248725336, 249512779715.9789], [1773249022828, 250411164071.34924], [1773249362144, 250411164071.34924], [1773249611856, 250288270444.8294], [1773249920915, 250353732113.15305], [1773250223780, 251416192685.8657], [1773250521185, 251001619786.15213], [1773250837091, 250263997437.47037], [1773251151188, 249660113777.5525], [1773251411737, 249732397317.7107], [1773251716891, 249841010845.1529], [1773252013083, 249284277609.8445], [1773252334359, 249663791599.12048], [1773252660685, 249663791599.12048], [1773252933873, 249342994451.53928], [1773253200637, 249342994451.53928], [1773253522005, 249998198050.51813], [1773253945148, 250217656171.21664], [1773254160572, 250217656171.21664], [1773254501205, 250411360001.85583], [1773254750702, 249661016610.41592], [1773255022325, 249898165787.42725], [1773255343842, 250442007218.46027], [1773255710516, 250655454359.811], [1773255960717, 250335372879.13892], [1773256308277, 250330087420.40335], [1773256571756, 250330087420.40335], [1773256805807, 249924351309.0181], [1773257103457, 250228373615.99], [1773257425578, 250406362825.14417], [1773257712294, 250138340986.20123], [1773258000565, 250638593064.59683], [1773258360620, 250199757573.98782], [1773258660606, 250380259588.62738], [1773258941885, 250642414353.1615], [1773259241374, 250430088620.71097], [1773259548100, 250216841820.30212], [1773259801107, 250072718640.09854], [1773260150646, 250072718640.09854], [1773260446665, 249883444176.37027], [1773260760469, 249875709558.10922], [1773261045926, 249732213469.01718], [1773261321668, 249747161477.4795], [1773261624602, 249872084987.334], [1773261917066, 249885646800.08298], [1773262221983, 249918262011.66547], [1773262536778, 249582368544.5957], [1773262835716, 249471535660.04657], [1773263111641, 249677963323.96484], [1773263441756, 249797990453.3971], [1773263753231, 249716702563.19043], [1773264093150, 249298240670.167], [1773264313667, 249348691527.1261], [1773264651554, 249364834149.93842], [1773264942107, 249546327218.8958], [1773265245600, 249789034178.97797], [1773265532804, 249722173540.8561], [1773265874240, 249658831366.75192], [1773266120750, 249948292623.11035], [1773266471567, 250198895732.53885], [1773266734483, 250008239879.37936], [1773267043713, 250096039168.15662], [1773267363178, 250096039168.15662], [1773267613553, 250848985600.78885], [1773267912501, 250213684656.4288], [1773268232948, 250037125228.81613], [1773268511424, 249766793843.31628], [1773268813292, 249038761094.18396], [1773269124161, 249010161740.0668], [1773269426458, 249215809508.04422], [1773269731890, 248910330603.65686], [1773270080569, 248830243089.82077], [1773270341226, 249046133801.3769], [1773270714104, 249078562118.90048], [1773270960526, 249078562118.90048], [1773271313087, 248639950155.6725], [1773271560836, 248578380911.7652], [1773271820602, 248548581018.38586], [1773272124836, 248299719521.03366], [1773272453574, 248419350894.60764], [1773272745294, 248349980320.05432], [1773273031999, 247369558309.9952], [1773273332053, 247646084116.33203], [1773273646206, 247553922388.4736], [1773273940875, 247713225259.2128], [1773274241757, 247713225259.2128], [1773274542941, 247838684042.425], [1773274881885, 247838684042.425], [1773275163933, 247931190204.75284], [1773275480707, 247955396869.43213], [1773275731183, 247834622008.9407], [1773276023576, 247892619545.44086], [1773276333299, 248166486442.2944], [1773276613470, 248065948161.49936], [1773276938973, 248099901580.61697], [1773277242533, 248162279862.6598], [1773277512268, 247414292124.5696], [1773277816583, 246686295980.84515], [1773278141929, 246686295980.84515], [1773278431221, 247362894684.68118], [1773278745094, 247241780955.54675], [1773279050928, 247352069243.98935], [1773279353007, 247037545938.84503], [1773279666626, 247001373178.64963], [1773280003629, 247387037713.553], [1773280252012, 247570072161.45624], [1773280512107, 247183879409.7036], [1773280811108, 246904023615.7266], [1773281144382, 246861306351.51877], [1773281445996, 246902012747.21973], [1773281751111, 246902012747.21973], [1773282101525, 246760363318.3321], [1773282360461, 245935706775.51077], [1773282691218, 246246257776.34586], [1773282960869, 245919425790.54156], [1773283271639, 245663264487.5732], [1773283560666, 244999094859.9473], [1773283841898, 245143102255.404], [1773284152869, 244365713957.55432], [1773284489561, 244439149846.81827], [1773284715141, 244545906518.60324], [1773285012741, 244589605253.1465], [1773285316134, 244490368101.7831], [1773285616521, 244490368101.7831], [1773285920843, 244660533127.77515], [1773286217140, 244925516905.1283], [1773286512243, 244921681885.71457], [1773286824363, 245362772219.40152], [1773287111122, 245210434444.28476], [1773287400615, 244008951491.33694], [1773287713617, 244059859175.50027], [1773288013726, 244186614494.59274], [1773288347351, 244425300420.63474], [1773288660728, 244748691705.9599], [1773288924098, 244748691705.9599], [1773289241120, 244801923601.93085], [1773289535487, 244813209613.3929], [1773289813069, 244589089818.19815], [1773290100808, 244721145015.46356], [1773290414155, 244235864545.86316], [1773290713150, 244566289293.82968], [1773291021433, 244332348214.15866], [1773291343504, 244152900350.74414], [1773291653797, 244164601020.09503], [1773291921434, 244163939880.4795], [1773292240684, 244342778148.4848], [1773292531311, 244342778148.4848], [1773292884576, 244272211278.4149], [1773293160610, 243878733864.78354], [1773293502992, 243896993812.15625], [1773293773248, 244021717393.5688], [1773294043250, 244206797740.3568], [1773294335828, 244652498453.41425], [1773294612371, 244507814038.16464], [1773294913114, 244284178855.5482], [1773295260631, 244500231101.77283], [1773295531453, 244442076065.40567], [1773295920528, 244442076065.40567], [1773296156314, 244802666532.79846], [1773296453220, 244802666532.79846], [1773296731238, 244802666532.79846], [1773297033013, 244917268451.166], [1773297321842, 245015185482.339], [1773297722539, 244864211898.56903], [1773297951950, 244918622588.48618], [1773298253665, 244829936219.6374], [1773298562313, 244877491070.9343], [1773298843367, 245026930539.52368], [1773299132180, 245063603450.87415], [1773299453439, 244918441981.243], [1773299782564, 244918441981.243], [1773300060538, 244960024552.98154], [1773300360836, 245064792470.40118], [1773300653687, 245392657294.96863], [1773300931503, 245791163343.05182], [1773301233755, 245826288802.06543], [1773301510629, 245776044451.8863], [1773301822013, 245936596646.63068], [1773302124565, 246215919934.94235], [1773302442106, 246120793805.3881], [1773302741918, 246506863084.24042], [1773303054452, 246493938466.74936], [1773303376165, 246493938466.74936], [1773303660726, 246158448866.80524], [1773303952101, 247249744753.4638], [1773304254036, 246855588209.33395], [1773304571918, 246920514421.09952], [1773304871112, 246944821986.83356], [1773305160861, 246555067817.39465], [1773305510947, 247034327072.27487], [1773305760684, 247141229683.01648], [1773306041964, 247053152197.98187], [1773306352670, 247095098672.7709], [1773306732675, 247029570824.09174], [1773306954659, 247029570824.09174], [1773307204033, 246384332990.06485], [1773307503541, 246319702087.01865], [1773307821673, 246332278601.70178], [1773308113364, 246413096475.5471], [1773308421862, 246436686912.35712], [1773308727328, 247572800851.41495], [1773309013783, 248149603794.75507], [1773309340837, 247967275584.99988], [1773309647234, 248117457428.88602], [1773309960542, 248257223955.76727], [1773310251874, 248104610735.25027], [1773310512238, 247986420956.5629], [1773310822499, 248293313913.82562], [1773311120834, 248764735611.14557], [1773311421572, 248738412424.7046], [1773311714987, 249272996003.23294], [1773312015562, 249735239528.07126], [1773312304309, 249915860599.24884], [1773312642189, 250180547023.4635], [1773312943378, 249890055157.5256], [1773313251556, 249940028121.2451], [1773313543170, 249749364724.91772], [1773313811016, 249718580442.90924], [1773314122222, 249845760141.72177], [1773314422713, 249832698775.58966], [1773314731614, 250031514629.195], [1773315040886, 249750338191.4727], [1773315343446, 249762888811.15765], [1773315632563, 250220742933.56165], [1773315960658, 250371944532.25412], [1773316260573, 249961032444.44443], [1773316513314, 249240115545.14746], [1773316842767, 248821781240.14255], [1773317146983, 248934053382.9771], [1773317440698, 248934053382.9771], [

                timestamp        price    market_cap  total_volume
0 2026-03-11 14:50:10.641  2069.560668  2.502684e+11  2.120448e+10
1 2026-03-11 14:55:10.796  2067.786517  2.495653e+11  2.026655e+10
2 2026-03-11 15:01:23.284  2064.125687  2.493105e+11  2.058198e+10
3 2026-03-11 15:05:15.517  2056.799683  2.488468e+11  1.976221e+10
4 2026-03-11 15:10:33.588  2051.687934  2.480950e+11  1.791519e+10
5 2026-03-11 15:16:36.864  2045.741542  2.480950e+11  1.682685e+10
6 2026-03-11 15:20:11.654  2048.313716  2.470558e+11  1.904132e+10
7 2026-03-11 15:25:53.000  2056.114305  2.480342e+11  2.013414e+10
8 2026-03-11 15:30:54.951  2049.846698  2.478955e+11  2.007875e+10
9 2026-03-11 15:35:11.499  2039.939015  2.456817e+11  2.021689e+10

In [ ]:
def extract_coin_list(as_frame = False): 
    end_point = "/coins/list"
    url = BASE_URL + end_point   
    headers = {
    'accept': 'application/json',
    'x-cg-demo-api-key':API_KEY
    }
   
    response = requests.get(url, headers=headers)
    if as_frame: 
        return pd.DataFrame(response.json())

    return response.json()

def extract_market_chart(coin_id, vs_currency = 'usd', days = 1): 
    # function pulls crypto prices every 5 minute
    endpoint = f'/coins/{coin_id}/market_chart'
    url = BASE_URL + endpoint
    
    params = {
        'vs_currency': 'usd',
        'days': 1
    }

    headers = {

    'accept': "application/json",
    'x-cg-demo-api-key': API_KEY

    }

    response = requests.get(url, headers=headers, params=params)
    return  response.json()


def tranform_market_chart(coin_id, data): 
    prices = data['prices']
    market_caps = data['market_caps']
    total_volumes   = data['total_volumes']
    df_prices = pd.DataFrame(prices, columns=['timestamp', 'price'])
    df_market_caps = pd.DataFrame(market_caps, columns = ['timestamp', 'market_cap'] )
    df_total_volumes = pd.DataFrame(total_volumes, columns= ['timestamp', 'total_volume'])

    df_market_chart= (

    df_prices.merge(df_market_caps, on='timestamp', how='inner')
    .merge(df_total_volumes, on='timestamp', how='inner')
    )
    df_market_chart['timestamp'] = pd.to_datetime(df_market_chart['timestamp'], unit='ms')
    df_market_chart['coin_id'] = coin_id

    return df_market_chart


def load_df_to_db(df, table_name, table_schema, engine):

    df.to_sql(table_name,engine, if_exists='append', index = False, schema=table_schema )